### ISSUE TITLE
<+> undocumented in the wiki

### ISSUE THREAD

**Issue by Grahack** [blancas/kern#10]
Hi,
`<+>` is used in the examples of `optional` [here](https://github.com/blancas/kern/wiki/Parser-Combinators) but was not documented before.

Thanks.

**Comment by Grahack** [comment]
In fact it's documented later in the page.

**Comment by blancas** [comment]
Looks like `optional` isn't used between those two, so it could go at the bottom of the section and avoid confusion. Thanks for the report.

**Comment by blancas** [comment]
Done.
