### ISSUE TITLE
Parsing math expressions

### ISSUE THREAD

**Issue by Grahack** [blancas/kern#11]
Hi,
Is there someone that has written a good (and correct!) base for parsing math expressions with Kern?
Thanks.

**Comment by blancas** [comment]
I did a little something with the HOC language, which you may have seen, but I'm not aware of anything more specific.

https://github.com/blancas/kern/blob/master/src/main/resources/hoc.clj

**Comment by blancas** [comment]
Let me know if you need something else; will be happy to assist you.
