### ISSUE TITLE
Warning about the overriding of `cat`

### ISSUE THREAD

**Issue by Grahack** [blancas/kern#12]
Hi,
In [kern.core](https://github.com/blancas/kern/blob/master/src/main/clojure/blancas/kern/core.clj), you type `(defn- cat...` and a warning bubbles up:

    WARNING: cat already refers to: #'clojure.core/cat in namespace: blancas.kern.core,
                       being replaced by: #'blancas.kern.core/cat

From a quick investigation, this `cat` is only used once.

Would you consider adding `(:refer-clojure :exclude [cat])` in the `kern.core` declarations?

Thanks.

(defn- cat

**Comment by blancas** [comment]
Sorry for the delay, hadn't check for a while. I'll be sure to put in a fix soon.

**Comment by blancas** [comment]
Done. Put out a rel 1.0.0 on clojars.

**Comment by Grahack** [comment]
Works indeed. Many thanks.
