### ISSUE TITLE
CompilerException thrown on `times` parser with n = 1

### ISSUE THREAD

**Issue by f-f** [blancas/kern#13]
Reproducing: `(run (times 1 letter) "a")`
Behaviour: throws a `CompilerException clojure.lang.ArityException: Wrong number of args (1) passed to: core/<*>`
Expected behaviour: parsing of one letter :) 

I would happily submit a PR for this (bug is in the implementation of `times`: checks `(pos? n)`, but `<*>` requires atleast two arguments)! Fix should be reducing the minimum arity of `<*>` to 1. Correct?

**Comment by blancas** [comment]
Sorry for the delay. I'll look at this ASAP.

**Comment by blancas** [comment]
I like your idea of reducing `<*>`'s arity to 1. The lib is missing the ability to apply any number of operators, it's either 1 or 2+.

This will also allow to have a shorter definition for `<+>` and fix a problem I just found there:
```
(run (<+> letter) "ab")
; => ""
```
This code seems to work with this and your reported bug:
```clojure
(defn <*> [p & more]
  (fn [s]
    (loop [s1 (assoc s :value [] :empty true) ps (cons p more)]
      (let [s2 (cat (first ps) s1)]
        (if (and (:ok s2) (next ps))
          (recur s2 (next ps))
          s2)))))

(defn <+> [p & more]
  (<$> (comp join flatten) (apply <*> p more)))
```
I should be able to put the fix and add tests over the weekend.

**Comment by blancas** [comment]
```
Sending org/blancas/kern/1.1.0/kern-1.1.0.pom (4k)
    to https://clojars.org/repo/
Sending org/blancas/kern/1.1.0/kern-1.1.0.jar (27k)
    to https://clojars.org/repo/
Sending org/blancas/kern/1.1.0/kern-1.1.0.jar.asc (1k)
    to https://clojars.org/repo/
Sending org/blancas/kern/1.1.0/kern-1.1.0.pom.asc (1k)
    to https://clojars.org/repo/
```

**Comment by f-f** [comment]
Looks great, thanks!

**Comment by f-f** [comment]
Thanks!
