### ISSUE TITLE
Poor error messages when mis-using bind

### ISSUE THREAD

**Issue by shepheb** [blancas/kern#17]
If the value to `bind` is not a function call (for example if you forget to wrap with `(return ...)`) you get one of two obscure error messages:

```
=> (use 'blancas.kern.core)
=> (def p (bind [_ (token* "foo")] 2))
=> (run p "foo")
ClassCastException java.lang.Long cannot be cast to clojure.lang.IFn  blancas.kern.core/>>=/fn--9647 (core.clj:379)
```
That's not so bad - I provided a Long where a IFn was expected.

This is worse:

```
=> (use 'blancas.kern.core)
=> (def p (bind [f (token* "foo")] { :some 'map }))
=> (run p "foo")
line null column null                                                                

nil
```

It would probably be a good idea to check `list?` on that last argument of `bind`.

**Comment by blancas** [comment]
@shepheb I'm going to experiment with this change, and some possible error detection. The typical case of `bind` always seem to end with `return` though it's not necessary, it can be any parser. But this change will clean up the user's code.

If a `bind` binds a name to a regular value, or returns a regular value --in both cases anything but a function-- it will call `return` on those values.

```Clojure
user=> (def p (bind [_ (token* "foo")] 2))
#'user/p
user=> (run p "foo")
2
nil
user=> (def p (bind [f (token* "foo")] { :some 'map }))
#'user/p
user=> (run p "foo")
{:some map}
user=> (def p (bind [foo 12345 f (token* "foo")] { :some foo }))
#'user/p
user=> (run p "foo")
{:some 12345}
nil
```
This last one example being equivalent to, but simpler than:
```Clojure
user=> (def p (bind [foo (return 12345) f (token* "foo")] (return { :some foo })))
#'user/p
user=> (run p "foo")
{:some 12345}
nil
```

**Comment by blancas** [comment]
The auto-lift in `>>=` and `bind` should reduce most cases like the ones reported here.
